# Generated by Django 5.2.7 on 2025-10-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(upload_to='skills/images/'),
        ),
    ]
